# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMCWeek8' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UMCWeek8
  pod 'Firebase'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseStorage'

end
