# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMCweek7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UMCweek7
pod 'KakaoSDKUser' # 카카오 로그인, 사용자 관리
pod 'KakaoSDKAuth' # 사용자 인증
end
